(define bar 3)
(define (foo x y) 1)
(define x+ (+ 1 2))
(define y+ (+ (+ 1 2) 3))
(define z+ (+ (+ 1 2) (+ 2 3) 4))
(define (add x y) (+ x y))
(define x-add (add 1 2))
(define y-add (add (add 1 2) 3))
(define z-add (add (add 1 2) (add (add 2 3) 4)))
(add (+ 1 2) 3)
(add (+ 1 2) 3)
(define (f x) x)
(+ 2 3)
(let* ([a (+ 1 2)]) (add a a))
(let* ([a (add 1 2)]) (add a a))
(let* ([a (add 1 2)] [b (+ 3 4)]) (+ a b))
; (let* ([x (let* ([a 1]) a)]) a)  ; TODO make this use of `a` unbound
